/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>

int main(void)
{


	uint32_t* GPIOB_portmode = (uint32_t *) 0x40020400;
	uint32_t* RCC_clocken = (uint32_t *) 0x40023830;
	uint32_t* GPIOB_out = (uint32_t *) 0x40020414;


	//Enable GPIOB clock, bit 1 to '1'
	*RCC_clocken |= (1 << 1); //Shift 1 two positions
	//OR using Bitmask
	//*RCC_clocken |= 0x2;

	//Set GPIOB bank as output
	//
	*GPIOB_portmode |= (1 << 28); //Enable PORTB14
	*GPIOB_portmode |= (1 << 14); //Enable PORTB7
	*GPIOB_portmode |= (1 << 0); //Enable PORTB0
	//OR using a bitmask
	//*GPIOB_portmode |= 0x10006001;


	//Switch value LD0
	*GPIOB_out ^= (1 << 0);
	//Switch value LD2
	*GPIOB_out ^= (1 << 7);
	//Switch value LD3
	*GPIOB_out ^= (1 << 14);
	//Switch value LD0
	*GPIOB_out ^= (1 << 0);
	//Switch value LD2
	*GPIOB_out ^= (1 << 7);
	//Switch value LD3
	*GPIOB_out ^= (1 << 14);


	for(;;);
}
